name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd project
        npm install --legacy-peer-deps
    
    - name: Setup Expo CLI
      run: |
        npm install -g @expo/cli
        npm install -g eas-cli
    
    - name: Create Expo account and build
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        cd project
        expo login -u $EXPO_TOKEN
        eas build --platform android --non-interactive --wait
